module.exports = {
  projects: [
    '<rootDir>/apps/cree-web',
    '<rootDir>/apps/cree-mobile',
    '<rootDir>/apps/cree-desktop',
    '<rootDir>/libs/cree/home/feature',
    '<rootDir>/libs/cree/library/feature',
    '<rootDir>/libs/cree/workspace/feature',
    '<rootDir>/libs/cree/courses/feature',
    '<rootDir>/libs/cree/user-profile/feature',
    '<rootDir>/libs/cree/page-not-found/feature',
    '<rootDir>/libs/cree/home/shell-web',
    '<rootDir>/libs/cree/library/shell-web',
    '<rootDir>/libs/cree/workspace/shell-web',
    '<rootDir>/libs/cree/courses/shell-web',
    '<rootDir>/libs/cree/user-profile/shell-web',
    '<rootDir>/libs/cree/page-not-found/shell-web',
    '<rootDir>/libs/cree/home/shell-desktop',
    '<rootDir>/libs/cree/home/shell-mobile',
    '<rootDir>/libs/cree/courses/data-access',
    '<rootDir>/libs/cree/shared/ui-components',
    '<rootDir>/libs/cree/shared/ui-icons',
    '<rootDir>/libs/cree/shared/ui-pipes',
    '<rootDir>/libs/cree/core/web-layout',
    '<rootDir>/libs/cree/core/mobile-layout',
    '<rootDir>/libs/cree/core/desktop-layout',
  ],
};
